import "../styles/globals.css";
import Head from "next/head";
import Header from "../components/Header";
import Sidebar from "../components/Sidebar";

function MyApp({ Component, pageProps }) {
  return (
    <>
      <Head>
        <title>Spotify Next13</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="bg-spotify-black min-h-screen text-gray-300">
        <Header />
        <Sidebar />
        <main>
          <Component {...pageProps} />
        </main>
      </div>
    </>
  );
}

export default MyApp;
